### ISSUE TITLE
Miss interpreting id?

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer-editor-service#26]
I have the following section of html in my element template
```
     <section id="hero_target" class="main-heading">
          <div class="heading">[[_makeHeading(clinic,route.params.date)]]</div>
          <paper-icon-button
            on-tap="_setFullOn"
            icon="pas:zoom-in"
            hidden$="[[subRoute.active]]"></paper-icon-button>
          <paper-icon-button
            on-tap="_setFullOff"
            icon="pas:zoom-out"
            hidden$="[[!subRoute.active]]"></paper-icon-button>
          <paper-icon-button
            on-tap="_openDrawer"
            icon="pas:info-outline"></paper-icon-button>
      </section>
  
```
As I mouse over the start of the `<paper-icon-button>` tag the following pops up in the output

```
[Error - 09:01:25] Error: Expected to find at most one element with id paper-icon-button but found 2.
    at Document.getOnlyAtId (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/model/document.js:156:19)
    at LocalEditorService.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/editor-service/local-editor-service.js:157:33)
    at next (<anonymous>)
    at fulfilled (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/editor-service/local-editor-service.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Using vscode

**Comment by rictic** [comment]
The `id` there isn't the html attribute `id`, it's the registered tagName of the custom element.

Are you doing anything unusual with your imports (like including hashes or query params in any import urls, or using multiple bower component directories)?

It's also a problem that this is throwing an exception that pops up the output panel. Reopened https://github.com/Polymer/vscode-plugin/issues/15

**Comment by akc42** [comment]
@rictic Nothing out of the ordinary with the content above.  The element itself that this is within is also loaded with a standard html import, but the level above that was loaded via lazy-import (ie that new behavior you recently announced at the Polymer Summit)
