### ISSUE TITLE
Rapid Backspacing can throw up an "already exists" error for file you are editing

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer-editor-service#27]
Using vscode, I quite frequently get the following pop up in an OUTPUT window from polymer-ide.

```
[Error - 13:59:20] Error: Internal error: document app/src/pas-appointments-day.html already exists
    at Analyzer._makeDocument (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:147:19)
    at Analyzer.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:132:39)
    at next (<anonymous>)
    at fulfilled (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[Error - 13:59:20] Error: Internal error: document app/src/pas-appointments-day.html already exists
    at Analyzer._makeDocument (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:147:19)
    at Analyzer.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:132:39)
    at next (<anonymous>)
    at fulfilled (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

etc etc ........................
```
It happens on back-delete.

I suspect I am getting one new message per key press, but it has to be keyboard repeat to go fast enough to trigger it, so cannot be sure.  It doesn't seem to trigger in text or element attributes - but it seems to wait until you are in the actual element name. This name doesn't have to be real.

If you stop, and try and repeat it, it doesn't happen again until you clear and close the output window. Then its easily repeatable.

**Comment by akc42** [comment]
I am getting exactly the same error when I mistyping rapidly forwards in a `<link rel="import"> tag typing the href.

Like the previous entry, it won't repeat once its occurred and I've stopped until I clear the OUTPUT window.

**Comment by TimvdLippe** [comment]
Can confirm I have seen this error pop up in the console of Atom.

**Comment by rictic** [comment]
Yep, this is a caching issue, I'm looking into it now. Same underlying issue that's causing a number of related issues including https://github.com/Polymer/polymer-editor-service/issues/28

I've got a repro of it at https://github.com/Polymer/polymer-analyzer/pull/390 and I'm working through a solution.
